#ifndef USBCONFIG_TOP_H
#define USBCONFIG_TOP_H

#define CONFIG_USB_HAS_SERIAL 1
#define CONFIG_USB_CFG_MAX_BUS_POWER 100
#define CONFIG_USB_CFG_DEVICE_CLASS 0x0

#define CONFIG_USB_HAS_DEVNAME 1
#define CONFIG_USB_CFG_SUPPRESS_INTR_CODE 1
#define CONFIG_USB_CFG_INTERFACE_SUBCLASS 0x0

#define CONFIG_AVRDUDE_PROG_USBASP 1

#define CONFIG_USB_CFG_DEVICE_SUBCLASS 0x0
#define CONFIG_USB_CFG_INTR_POLL_INTERVAL 50
#define CONFIG_USB_CFG_INTERFACE_PROTOCOL 0x00

#define CONFIG_USB_HAS_VENDORNAME 1
#define CONFIG_USB_ONLY_INCLUDE 1
#define CONFIG_USB_CFG_INTERFACE_CLASS 0x3
#define CONFIG_USB_CFG_DEVICE_VERSION 0x0002
#define CONFIG_USB_CFG_HID_REPORT_DESCRIPTOR_LENGTH 42
#define CONFIG_USB_CFG_HAVE_INTRIN_ENDPOINT 1
#define CONFIG_USB_CFG_IMPLEMENT_FN_WRITE 1


//#define USB_CFG_VENDOR_ID 0x50,0x1d
//#define USB_CFG_DEVICE_ID 0x32,0x60
#define USB_CFG_DEVICE_VERSION 0x02,0x00

#include "usbconfig.cmake.h"
#include "usbconfig-base.h"

#endif /* end of include guard: USBCONFIG_TOP_H */
