set(VUSB_DIR packages/v-usb)


set(SRC_vusb ${VUSB_DIR}/usbdrv/usbdrvasm.S)
set(INC_vusb ${VUSB_DIR})
set(CFLAGS_vusb -Wno-unused-function)

function(generate_config_vusb target)
  message(STATUS "Generating vusb config for ${target}")
  set(conf ${CMAKE_BINARY_DIR}/include-${target}/usbconfig.cmake.h)
  file(WRITE ${conf} "/* Autogenerated. Do not edit */\n")
  file(APPEND ${conf} "#ifndef _USB_UHID_CONFIG\n")
  file(APPEND ${conf} "#define _USB_UHID_CONFIG\n")


  defconf(CONFIG_USB_CFG_DMINUS_BIT ${CONFIG_USB_DMINUS_BIT})
  defconf(CONFIG_USB_CFG_DPLUS_BIT ${CONFIG_USB_DPLUS_BIT})
  defconf(USB_CFG_IOPORTNAME ${CONFIG_USB_IOPORT})

  defu16(USB_CFG_VENDOR_ID ${CONFIG_USB_VID})
  defu16(USB_CFG_DEVICE_ID ${CONFIG_USB_PID})

  defstr(USB_CFG_SERIAL_NUMBER ${CONFIG_USB_SERIAL})
  defstr(USB_CFG_VENDOR_NAME ${CONFIG_USB_VENDOR})
  defstr(USB_CFG_DEVICE_NAME ${CONFIG_USB_PRODUCT})

  defconf(CONFIG_USB_ONLY_INCLUDE 1)

  generate_common_config()
  file(APPEND ${conf} "#endif\n")
endfunction()
